spring:
  application:
    name: customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: false
  datasource:
    url: postgresql://localhost:5432/sf_customer
    driver: org.postgresql.Driver
    username: postgres
    password: postgres

server:
  port: 8080
    
info:
  app:
   name: Customer
   description: "Single vendor ecommerce app Customer Application"
   version: "1.0.0"