global:
  scrape_interval: 15s

scrape_configs:
  - job_name: gatewayserver
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - localhost:9040
 #         - host.docker.internal:9040 #for docker