spring:
  application:
    name: order
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: false
  profiles:
    active: default
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:9030/}"
  cloud:
    function:
      definition: inventoryResult;paymentResult;inventoryResultDlq;paymentResultDlq
    stream:
      bindings:
        paymentCommand-out-0:
          destination: payment.command
        inventoryCommand-out-0:
          destination: inventory.command
        paymentResult-in-0:
          destination: payment.result
          group: order
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2
            back-off-max-interval: 10000
        inventoryResult-in-0:
          destination: inventory.result
          group: order
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-multiplier: 2
            back-off-max-interval: 10000
        inventoryResultDlq-in-0:
          destination: inventory.result.order.dlq
          group: order-dlq
        paymentResultDlq-in-0:
          destination: payment.result.order.dlq
          group: order-dlq
      rabbit:
        bindings:
          paymentResult-in-0:
            consumer:
              autoBindDlq: true
              republishToDlq: true
              dlq-ttl: 604800000
          inventoryResult-in-0:
            consumer:
              autoBindDlq: true
              republishToDlq: true
              dlq-ttl: 604800000
  lifecycle:
    timeout-per-shutdown-phase: 60s
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 9000
  shutdown: graceful
   
info:
  app:
    name: Order
    description: "Single vendor ecommerce app Order Application"
    version: "1.0.0"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
    rabbit:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
    prometheus:
      access: read-only
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
      slo:
        http.server.requests:
          - 100ms
          - 250ms
          - 500ms
          - 1s
          - 2s
      
logging:
  level:
    com.storefront: INFO
  pattern:
    console: >
      %d{yyyy-MM-dd HH:mm:ss.SSS}
      [%thread]
      %-5level
      [%X{correlationId}]
      %logger{36}
      - %msg%n